package com.example.programacion4proyectofinal.Utils.UserData;

/**
 * Enum class with a last name of a passanger
 */
public enum LastName {
    GARCIA, RODRIGUEZ, MARTINEZ, GONZALEZ, LOPEZ, HERNANDEZ, PEREZ, SANCHEZ, ROMERO, FERNANDEZ,
    DIAZ, RAMIREZ, TORRES, VARGAS, CRUZ, ORTEGA, MORALES, CASTILLO, RUIZ, JIMENEZ,
    FLORES, NAVARRO, GOMEZ, GUZMAN, ORTIZ, SILVA, GUTIERREZ, CASTRO, SANTOS, RODRIGUES,
    OLIVEIRA, MENDOZA, LIMA, ARAYA, PACHECO, ALVAREZ, VEGA, CASTELLANOS, REYES, CAMPOS,
    PADILLA, ARIAS, GONZALES, HERRERA, RIVERA, GUERRERO, FERREIRA, SOTO, AGUILAR, PEÑA,
    ACOSTA, MARTINS, RIVAS, SALAZAR, MORENO, DELGADO, PARRA, ANDRADE, SALDANA, CORDOVA,
    BARROS, ESPINOZA, OCHOA, URIBE, MONTERO, FARIAS, VILLEGAS, BARRERA, ARAVENA, FIGUEROA,
    SEPULVEDA, MIRANDA, PALMA, ALMEIDA, MACHADO, PARDO, MENDEZ, VALENZUELA, BUSTOS, FONSECA,
    CONTRERAS, GALVEZ, VILLARREAL, CARRILLO, PINTO, ZAPATA, CORREA, BRITO, ESCOBAR,
    MONCADA, LEAL, HURTADO, VALDES, VILLANUEVA, TOLEDO, ESPINO, NAVARRETE, MUÑOZ,
    CORTES, GUERRA, PINEDA, QUINTANA, AGUILERA, ROSALES, SALCEDO, SANHUEZA, VIDAL,
    ESPINOSA, TAPIA, ORELLANA, CABRERA, SOLIS, COLLAO, ABARCA, HERRERO

}
