package com.example.programacion4proyectofinal.Utils.UserData;

/**
 * Enum class with a name of a passenger
 */
public enum Name {
    MARIA, JOSE, ANA, CARLOS, LUCIA, JUAN, LAURA, MIGUEL, SOFIA, DIEGO,
    PAULA, PEDRO, CAMILA, ANDRES, VALERIA, ALEJANDRO, NATALIA, FRANCISCO, ISABELLA, RAFAEL,
    JULIA, FERNANDO, DANIELA, ALEXANDER, MARTINA, LEONARDO, ELENA, ADRIAN, VALENTINA,
    GABRIEL, VALENTIN, SOLEDAD, GUSTAVO, CONSTANZA, RAMON, EVA, EMILIO, LILIANA,
    AGUSTIN, JULIANA, FELIPE, CATALINA, RICARDO, CLARA, NICOLAS, MARIANA, ESTEBAN,
    MARTA, BRUNO, GISELA, IGNACIO, VICTORIA, ARTURO, ANTONIA, JOAQUIN, CARMEN,
    MANUEL, MONICA, LUIS, ANDREA, JORGE, MERCEDES, SERGIO, LUCIANA, OSCAR,
    AMANDA, RODRIGO, VALERIO, ANGELICA, FELIX, VANESA, ADOLFO, CLAUDIA, EDUARDO,
    MONTSERRAT, FERNANDA, ROBERTO, GLORIA, MAURICIO, PAULINA, HECTOR, DANIEL, AURORA,
    RENE, JAZMIN, LEANDRO, SOFIE, RUBEN, GABRIELA, VICTOR, JESSICA, CESAR,
    ROSA, GERMAN, VERONICA, HERNAN, MARCELA, WALTER, CECILIA, FABIAN,
    SUSANA, ARIEL, SANDRA, JAVIER, LUCAS, LETICIA, TOMAS, MIRANDA,
    SEBASTIAN, RAUL, SILVIA, CARMELO, CAROLINA, PABLO, OLGA, AITOR
}
