package com.example.programacion4proyectofinal.UserGenerator.UserData;

public enum LastName {
    SMITH, JOHNSON, WILLIAMS, BROWN, JONES, GARCIA, MILLER, DAVIS, RODRIGUEZ, MARTINEZ,
    HERNANDEZ, LOPEZ, GONZALEZ, WILSON, ANDERSON, TAYLOR, THOMAS, MOORE, JACKSON, MARTIN,
    LEE, PEREZ, THOMPSON, WHITE, HARRIS, SANCHEZ, CLARK, RAMIREZ, LEWIS, ROBINSON,
    WALKER, YOUNG, ALLEN, KING, WRIGHT, SCOTT, GREEN, BAKER, ADAMS, NELSON,
    CARTER, MITCHELL, ROBERTS, TURNER, PHILLIPS, CAMPBELL, PARKER, EVANS,
    EDWARDS, COOK, FLORES, MORRIS, GOMEZ, COOPER,RIVERA ,REED ,BAILEY ,BELL,
    RICHARDSON ,HOWARD ,COX ,WARD ,TORRES ,PETERSON ,GRAY ,JAMES ,WATSON ,
    BROOKS ,KELLY ,SANDERS ,PRICE ,BENNETT ,WOOD ,BARNES ,ROSS ,HENDERSON ,
    COLEMAN ,ALEXANDER ,WEST ,JORDAN ,OWENS ,REYNOLDS;
}
